# Generated by Django 3.2.25 on 2025-09-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
