# Generated by Django 3.2.25 on 2025-09-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fathername',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mothername',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
